const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const assets=path.resolve(__dirname,'../assets');
// Template/state unit tests. These are not browser layout or UI automation tests.
function render(query=''){
 const nodes=new Map(),events={},downloads=[];let lastBlob;
 const node=id=>{if(!nodes.has(id))nodes.set(id,{id,innerHTML:'',value:'',type:'search',classList:{add(){},remove(){},toggle(){}},addEventListener(name,fn){this[name]=fn;},setAttribute(){},setCustomValidity(){},checkValidity(){return true;},reportValidity(){},showModal(){this.open=true;},close(){this.open=false;},focus(){},select(){},setSelectionRange(){}});return nodes.get(id);};
 const document={documentElement:{},getElementById:node,addEventListener(name,fn){events[name]=fn;},querySelector(){return node('query');},body:{append(){}},createElement(){return {click(){downloads.push({filename:this.download,blob:lastBlob});},remove(){}};}};
 const location={search:query,pathname:'/iccarankings/dashboard.html',href:'https://example.test/iccarankings/dashboard.html'+query};let saved='';
 const ctx={document,location,URLSearchParams,history:{replaceState(a,b,url){saved=url;}},console,setTimeout,clearTimeout,navigator:{},Blob,URL:{createObjectURL(blob){lastBlob=blob;return 'blob:test';},revokeObjectURL(){}},MouseEvent:class{},window:null};ctx.window=ctx;ctx.scrollTo=()=>{};
 vm.createContext(ctx);for(const file of ['data.js','thailand.js','model.js','app.js'])vm.runInContext(fs.readFileSync(path.join(assets,file),'utf8'),ctx,{filename:file});
 return {html:node('app').innerHTML+node('view-content').innerHTML,node,events,downloads,saved:()=>saved,click:async data=>events.click({target:{closest:()=>({dataset:data,setAttribute(){}})}})};
}
test('all views render in both languages for all 11 supported years',()=>{for(const lang of ['th','en'])for(const view of ['overview','compare','policy','data','sources'])for(let year=2016;year<=2026;year++){const r=render(`?lang=${lang}&view=${view}&year=${year}`);assert.ok(!/NaN|undefined|Infinity/.test(r.html),`${view}/${year}/${lang}`);assert.ok(r.html.includes('Thailand Conventions Lab'));assert.ok(!r.html.includes('being prepared'));}});
test('2026 has a real empty state and no stale latest-year map',()=>{const r=render('?year=2026&lang=en');assert.ok(r.html.includes('2026 data is pending'));assert.ok(!r.node('view-content').innerHTML.includes('class="map-layout"'));});
test('shared filters survive reload and user text is escaped',()=>{const r=render('?year=2025&region=north&tier=large&q=%3Cscript%3E&trend=rank&start=2024&end=2026');assert.ok(r.saved().includes('trend=rank'));assert.ok(r.saved().includes('region=north'));assert.ok(r.html.includes('&lt;script&gt;'));assert.ok(!r.html.includes('<script>'));});
test('invalid URL input is constrained',()=>{const r=render('?year=1900&view=invalid&start=2025&end=2016&target=-1&horizon=0');assert.ok(r.saved().includes('year=2025'));assert.ok(r.saved().includes('view=overview'));assert.ok(!r.html.includes('NaN'));});

test('dashboard has a native Home link and shares its own route',()=>{for(const lang of ['th','en']){const r=render('?lang='+lang);assert.ok(r.html.includes('href="index.html'+(lang==='en'?'?lang=en':'')+'"'));assert.ok(r.saved().startsWith('/iccarankings/dashboard.html?'));}});
test('navigation, metrics, selection limits and dialogs update state',async()=>{const r=render('?lang=en');await r.click({view:'compare'});assert.ok(r.node('view-content').innerHTML.includes('Selected city trends'));await r.click({compare:'bkk'});assert.ok(r.node('toast').textContent.includes('up to 4'));await r.click({compare:'cm'});await r.click({compare:'bkk'});assert.ok(r.saved().includes('bkk'));await r.click({metric:'rank'});assert.ok(r.saved().includes('metric=rank'));await r.click({year:'2026'});assert.ok(r.saved().includes('year=2026'));await r.click({city:'bkk'});assert.equal(r.node('detail-dialog').open,true);await r.click({action:'close'});assert.equal(r.node('detail-dialog').open,false);});
test('country history and scenario exports are reachable',async()=>{const r=render('?lang=en&view=data');await r.click({table:'country'});assert.ok(r.node('view-content').innerHTML.includes('Full-year data pending'));await r.click({view:'policy'});await r.click({target:'204'});assert.ok(r.node('view-content').innerHTML.includes('+33'));assert.ok(r.saved().includes('target=204'));await r.click({action:'export'});assert.ok(r.node('detail-dialog').innerHTML.includes('hypothetical scenario CSV'));});
test('actual export handlers produce parseable files with filtered and missing observations',async()=>{const r=render('?lang=en&year=2025&region=north');await r.click({download:'cities'});let csv=await r.downloads.at(-1).blob.text();assert.equal(csv.split('\r\n').length,4);assert.ok(csv.includes('Chiang Mai'));assert.ok(!csv.includes('"Bangkok"'));await r.click({download:'country'});csv=await r.downloads.at(-1).blob.text();assert.ok(csv.includes('"2026","2569","",""'));assert.ok(csv.includes('"not_comparable"'));await r.click({download:'json'});const json=JSON.parse(await r.downloads.at(-1).blob.text());assert.equal(json.country[2025].n,171);assert.equal(json.country[2026].n,null);await r.click({download:'scenario'});csv=await r.downloads.at(-1).blob.text();assert.ok(csv.includes('"hypothetical_scenario","2025","171","2028","204","33"'));});
